-- ============================================================
-- CORE MODULE - Migration Script
-- Run this FIRST before all other modules
-- Covers: accounts, customer_types, customers, invoices, payments,
--         invoice_items, lookup tables (statuses)
-- ============================================================

-- ============================================================
-- UTILITY: set_updated_at() trigger function
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- LOOKUP TABLES (must exist before referencing tables)
-- ============================================================

-- invoice_statuses
CREATE TABLE IF NOT EXISTS public.invoice_statuses (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);
ALTER TABLE public.invoice_statuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.invoice_statuses FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.invoice_statuses (id, name) VALUES
    (1, 'draft'), (2, 'sent'), (3, 'partially_paid'),
    (4, 'paid'), (5, 'overdue'), (6, 'cancelled')
ON CONFLICT (name) DO NOTHING;

-- order_statuses
CREATE TABLE IF NOT EXISTS public.order_statuses (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);
ALTER TABLE public.order_statuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.order_statuses FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.order_statuses (id, name) VALUES
    (1, 'pending'), (2, 'confirmed'), (3, 'in_progress'),
    (4, 'completed'), (5, 'cancelled')
ON CONFLICT (name) DO NOTHING;

-- return_statuses
CREATE TABLE IF NOT EXISTS public.return_statuses (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);
ALTER TABLE public.return_statuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.return_statuses FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.return_statuses (id, name) VALUES
    (1, 'pending'), (2, 'approved'), (3, 'rejected'), (4, 'refunded')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 1. accounts  (Chart of Accounts)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.accounts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_code    text NOT NULL UNIQUE,
    name            text NOT NULL,
    account_type    text NOT NULL DEFAULT 'asset'
                    CHECK (account_type IN ('asset','liability','equity','revenue','expense')),
    account_subtype text NOT NULL DEFAULT 'cash'
                    CHECK (account_subtype IN (
                      'cash','bank','receivable','inventory','fixed_asset','other_asset',
                      'payable','accrued','loan','other_liability',
                      'capital','retained_earnings',
                      'sales','service_income','other_revenue',
                      'cost_of_goods','operating','salary','depreciation','other_expense'
                    )),
    parent_id       bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
    description     text,
    opening_balance numeric NOT NULL DEFAULT 0,
    balance         numeric NOT NULL DEFAULT 0,
    is_system       boolean NOT NULL DEFAULT false,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.accounts FOR ALL USING (true) WITH CHECK (true);

CREATE TRIGGER trg_accounts_updated_at
  BEFORE UPDATE ON public.accounts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 2. customer_types
CREATE TABLE IF NOT EXISTS public.customer_types (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name   text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.customer_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.customer_types FOR ALL USING (true) WITH CHECK (true);

-- 3. customers
CREATE TABLE IF NOT EXISTS public.customers (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL,
    store_name          text,
    email               text,
    phone               text,
    phone2              text,
    address             text,
    tax_number          text,
    notes               text,
    customer_type_id    bigint REFERENCES public.customer_types(id) ON DELETE SET NULL,
    is_active           boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.customers FOR ALL USING (true) WITH CHECK (true);

-- 4. invoices
CREATE TABLE IF NOT EXISTS public.invoices (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         bigint NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
    warehouse_id        bigint REFERENCES public.warehouses(id) ON DELETE SET NULL,
    invoice_number      text,
    invoice_date        timestamptz NOT NULL DEFAULT now(),
    total_amount        numeric NOT NULL DEFAULT 0,
    discount_amount     numeric NOT NULL DEFAULT 0,
    tax_amount          numeric NOT NULL DEFAULT 0,
    paid_amount         numeric NOT NULL DEFAULT 0,
    status_id           bigint NOT NULL DEFAULT 1 REFERENCES public.invoice_statuses(id) ON DELETE RESTRICT,
    notes               text,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.invoices FOR ALL USING (true) WITH CHECK (true);

-- 5. payments (customer payments)
CREATE TABLE IF NOT EXISTS public.payments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          bigint NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    account_id          bigint NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
    amount              numeric NOT NULL,
    date                timestamptz NOT NULL DEFAULT now(),
    method              text NOT NULL DEFAULT 'cash'
                        CHECK (method IN ('cash', 'bank', 'check')),
    notes               text,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.payments FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- ALTER existing tables (if they already exist without new columns)
-- ============================================================

-- Add missing columns to customers (if table already exists)
DO $$ BEGIN
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS phone2 text;
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS tax_number text;
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS notes text;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Add missing columns to payments (if table already exists)
DO $$ BEGIN
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS account_id bigint REFERENCES public.accounts(id) ON DELETE RESTRICT;
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS method text NOT NULL DEFAULT 'cash' CHECK (method IN ('cash', 'bank', 'check'));
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS created_by bigint REFERENCES public.employees(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- ============================================================
-- SEED: Default customer types
-- ============================================================
INSERT INTO public.customer_types (type_name) VALUES
    ('Retail'),
    ('Wholesale'),
    ('VIP')
ON CONFLICT (type_name) DO NOTHING;

-- ============================================================
-- INDEXES for performance
-- ============================================================

-- Customers
CREATE INDEX IF NOT EXISTS idx_customers_type ON public.customers(customer_type_id);
CREATE INDEX IF NOT EXISTS idx_customers_active ON public.customers(is_active);

-- Invoices
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON public.invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(status_id);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON public.invoices(invoice_date);

-- Payments
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON public.payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_account ON public.payments(account_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(date);

-- Accounts
CREATE INDEX IF NOT EXISTS idx_accounts_type ON public.accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_accounts_active ON public.accounts(is_active);
CREATE INDEX IF NOT EXISTS idx_accounts_code ON public.accounts(account_code);
CREATE INDEX IF NOT EXISTS idx_accounts_parent ON public.accounts(parent_id);
CREATE INDEX IF NOT EXISTS idx_accounts_subtype ON public.accounts(account_subtype);

-- ============================================================
-- 6. sales_returns (customer / sales returns)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sales_returns (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          bigint NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    invoice_item_id     bigint REFERENCES public.invoice_items(id) ON DELETE SET NULL,
    return_date         date NOT NULL DEFAULT CURRENT_DATE,
    quantity            integer NOT NULL DEFAULT 1,
    reason              text,
    refund_amount       numeric NOT NULL DEFAULT 0,
    status_id           bigint NOT NULL DEFAULT 1 REFERENCES public.return_statuses(id) ON DELETE RESTRICT,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sales_returns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.sales_returns FOR ALL USING (true) WITH CHECK (true);

-- Invoice Items
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      bigint NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    product_id      bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    product_unit_id bigint REFERENCES public.product_units(id) ON DELETE SET NULL,
    quantity        integer NOT NULL DEFAULT 1,
    unit_price      numeric NOT NULL DEFAULT 0,
    discount        numeric NOT NULL DEFAULT 0,
    total_price     numeric NOT NULL DEFAULT 0
);

ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.invoice_items FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON public.invoice_items(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_items_product ON public.invoice_items(product_id);

-- Sales Returns indexes
CREATE INDEX IF NOT EXISTS idx_sales_returns_invoice ON public.sales_returns(invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_returns_status ON public.sales_returns(status_id);
CREATE INDEX IF NOT EXISTS idx_sales_returns_date ON public.sales_returns(return_date);

-- ============================================================
-- SEED: Default Chart of Accounts
-- ============================================================
INSERT INTO public.accounts (account_code, name, account_type, account_subtype, is_system, opening_balance) VALUES
    -- Assets
    ('1001', 'Cash',                  'asset',     'cash',            true, 0),
    ('1002', 'Petty Cash',            'asset',     'cash',            true, 0),
    ('1100', 'Bank',                  'asset',     'bank',            true, 0),
    ('1200', 'Accounts Receivable',   'asset',     'receivable',      true, 0),
    ('1300', 'Inventory',             'asset',     'inventory',       true, 0),
    ('1400', 'Fixed Assets',          'asset',     'fixed_asset',     false, 0),
    ('1500', 'Prepaid Expenses',      'asset',     'other_asset',     false, 0),
    -- Liabilities
    ('2100', 'Accounts Payable',      'liability', 'payable',         true, 0),
    ('2200', 'Accrued Expenses',      'liability', 'accrued',         false, 0),
    ('2300', 'Loans Payable',         'liability', 'loan',            false, 0),
    ('2400', 'Tax Payable',           'liability', 'other_liability', false, 0),
    -- Equity
    ('3001', 'Owner Capital',         'equity',    'capital',         true, 0),
    ('3100', 'Retained Earnings',     'equity',    'retained_earnings', true, 0),
    -- Revenue
    ('4001', 'Sales Revenue',         'revenue',   'sales',           true, 0),
    ('4100', 'Service Income',        'revenue',   'service_income',  false, 0),
    ('4200', 'Other Revenue',         'revenue',   'other_revenue',   false, 0),
    -- Expenses
    ('5001', 'Cost of Goods Sold',    'expense',   'cost_of_goods',   true, 0),
    ('5100', 'Salaries & Wages',      'expense',   'salary',          true, 0),
    ('5200', 'Rent Expense',          'expense',   'operating',       false, 0),
    ('5300', 'Utilities Expense',     'expense',   'operating',       false, 0),
    ('5400', 'Depreciation Expense',  'expense',   'depreciation',    false, 0),
    ('5500', 'Office Supplies',       'expense',   'operating',       false, 0),
    ('5600', 'Marketing Expense',     'expense',   'operating',       false, 0),
    ('5700', 'Insurance Expense',     'expense',   'operating',       false, 0),
    ('5800', 'Bank Charges',          'expense',   'other_expense',   false, 0),
    ('5900', 'Other Expenses',        'expense',   'other_expense',   false, 0)
ON CONFLICT (account_code) DO NOTHING;
