-- ============================================================
-- CORE MODULE - Migration Script
-- Run this FIRST before all other modules
-- Covers: accounts, customer_types, customers, invoices, payments
-- ============================================================

-- 1. accounts (financial accounts: cash, bank)
CREATE TABLE IF NOT EXISTS public.accounts (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    account_type text NOT NULL DEFAULT 'cash'
                CHECK (account_type IN ('cash', 'bank')),
    balance     numeric NOT NULL DEFAULT 0,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.accounts FOR ALL USING (true) WITH CHECK (true);

-- 2. customer_types
CREATE TABLE IF NOT EXISTS public.customer_types (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name   text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.customer_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.customer_types FOR ALL USING (true) WITH CHECK (true);

-- 3. customers
CREATE TABLE IF NOT EXISTS public.customers (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL,
    store_name          text,
    email               text,
    phone               text,
    phone2              text,
    address             text,
    tax_number          text,
    notes               text,
    customer_type_id    bigint REFERENCES public.customer_types(id) ON DELETE SET NULL,
    is_active           boolean NOT NULL DEFAULT true,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.customers FOR ALL USING (true) WITH CHECK (true);

-- 4. invoices
CREATE TABLE IF NOT EXISTS public.invoices (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         bigint NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
    warehouse_id        bigint REFERENCES public.warehouses(id) ON DELETE SET NULL,
    invoice_number      text,
    invoice_date        timestamptz NOT NULL DEFAULT now(),
    total_amount        numeric NOT NULL DEFAULT 0,
    paid_amount         numeric NOT NULL DEFAULT 0,
    status_id           bigint NOT NULL DEFAULT 1 REFERENCES public.invoice_statuses(id) ON DELETE RESTRICT,
    notes               text,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.invoices FOR ALL USING (true) WITH CHECK (true);

-- 5. payments (customer payments)
CREATE TABLE IF NOT EXISTS public.payments (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          bigint NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    account_id          bigint NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
    amount              numeric NOT NULL,
    date                timestamptz NOT NULL DEFAULT now(),
    method              text NOT NULL DEFAULT 'cash'
                        CHECK (method IN ('cash', 'bank', 'check')),
    notes               text,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.payments FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- ALTER existing tables (if they already exist without new columns)
-- ============================================================

-- Add missing columns to customers (if table already exists)
DO $$ BEGIN
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS phone2 text;
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS tax_number text;
    ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS notes text;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- Add missing columns to payments (if table already exists)
DO $$ BEGIN
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS account_id bigint REFERENCES public.accounts(id) ON DELETE RESTRICT;
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS method text NOT NULL DEFAULT 'cash' CHECK (method IN ('cash', 'bank', 'check'));
    ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS created_by bigint REFERENCES public.employees(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- ============================================================
-- SEED: Default customer types
-- ============================================================
INSERT INTO public.customer_types (type_name) VALUES
    ('Retail'),
    ('Wholesale'),
    ('VIP')
ON CONFLICT (type_name) DO NOTHING;

-- ============================================================
-- INDEXES for performance
-- ============================================================

-- Customers
CREATE INDEX IF NOT EXISTS idx_customers_type ON public.customers(customer_type_id);
CREATE INDEX IF NOT EXISTS idx_customers_active ON public.customers(is_active);

-- Invoices
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON public.invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(status_id);
CREATE INDEX IF NOT EXISTS idx_invoices_date ON public.invoices(invoice_date);

-- Payments
CREATE INDEX IF NOT EXISTS idx_payments_invoice ON public.payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_payments_account ON public.payments(account_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(date);

-- Accounts
CREATE INDEX IF NOT EXISTS idx_accounts_type ON public.accounts(account_type);
CREATE INDEX IF NOT EXISTS idx_accounts_active ON public.accounts(is_active);

-- ============================================================
-- 6. sales_returns (customer / sales returns)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sales_returns (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          bigint NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    invoice_item_id     bigint REFERENCES public.invoice_items(id) ON DELETE SET NULL,
    return_date         date NOT NULL DEFAULT CURRENT_DATE,
    quantity            integer NOT NULL DEFAULT 1,
    reason              text,
    refund_amount       numeric NOT NULL DEFAULT 0,
    status_id           bigint NOT NULL DEFAULT 1 REFERENCES public.return_statuses(id) ON DELETE RESTRICT,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sales_returns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.sales_returns FOR ALL USING (true) WITH CHECK (true);

-- Sales Returns indexes
CREATE INDEX IF NOT EXISTS idx_sales_returns_invoice ON public.sales_returns(invoice_id);
CREATE INDEX IF NOT EXISTS idx_sales_returns_status ON public.sales_returns(status_id);
CREATE INDEX IF NOT EXISTS idx_sales_returns_date ON public.sales_returns(return_date);
