-- ============================================================
-- EMPLOYEES MODULE - Migration Script
-- Run this FIRST before suppliers module
-- ============================================================

-- 1. departments
CREATE TABLE IF NOT EXISTS public.departments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.departments FOR ALL USING (true) WITH CHECK (true);

-- 2. job_titles
CREATE TABLE IF NOT EXISTS public.job_titles (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text NOT NULL,
    department_id   bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    is_active       boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.job_titles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.job_titles FOR ALL USING (true) WITH CHECK (true);

-- 3. employees
CREATE TABLE IF NOT EXISTS public.employees (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          text NOT NULL,
    last_name           text NOT NULL,
    email               text,
    phone               text,
    address             text,
    national_id         text,
    hire_date           date NOT NULL DEFAULT CURRENT_DATE,
    end_date            date,
    employment_status   text NOT NULL DEFAULT 'active'
                        CHECK (employment_status IN ('active', 'on_leave', 'terminated')),
    department_id       bigint REFERENCES public.departments(id) ON DELETE SET NULL,
    job_title_id        bigint REFERENCES public.job_titles(id) ON DELETE SET NULL,
    base_salary         numeric NOT NULL DEFAULT 0,
    is_active           boolean NOT NULL DEFAULT true,
    auth_user_id        uuid,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.employees FOR ALL USING (true) WITH CHECK (true);

-- 4. roles
CREATE TABLE IF NOT EXISTS public.roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    description text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.roles FOR ALL USING (true) WITH CHECK (true);

-- 5. permissions
CREATE TABLE IF NOT EXISTS public.permissions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module      text NOT NULL,
    action      text NOT NULL CHECK (action IN ('create', 'read', 'update', 'delete')),
    description text,
    UNIQUE (module, action)
);

ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.permissions FOR ALL USING (true) WITH CHECK (true);

-- 6. role_permissions (M2M: roles <-> permissions)
CREATE TABLE IF NOT EXISTS public.role_permissions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         bigint NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    permission_id   bigint NOT NULL REFERENCES public.permissions(id) ON DELETE CASCADE,
    UNIQUE (role_id, permission_id)
);

ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.role_permissions FOR ALL USING (true) WITH CHECK (true);

-- 7. employee_roles (M2M: employees <-> roles)
CREATE TABLE IF NOT EXISTS public.employee_roles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    role_id     bigint NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
    UNIQUE (employee_id, role_id)
);

ALTER TABLE public.employee_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.employee_roles FOR ALL USING (true) WITH CHECK (true);

-- 8. salary_components
CREATE TABLE IF NOT EXISTS public.salary_components (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    type        text NOT NULL CHECK (type IN ('allowance', 'deduction')),
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.salary_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.salary_components FOR ALL USING (true) WITH CHECK (true);

-- 9. employee_salary_components (which components apply to each employee)
CREATE TABLE IF NOT EXISTS public.employee_salary_components (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id             bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    salary_component_id     bigint NOT NULL REFERENCES public.salary_components(id) ON DELETE CASCADE,
    amount                  numeric NOT NULL DEFAULT 0,
    is_percentage           boolean NOT NULL DEFAULT false,
    UNIQUE (employee_id, salary_component_id)
);

ALTER TABLE public.employee_salary_components ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.employee_salary_components FOR ALL USING (true) WITH CHECK (true);

-- 10. payroll (monthly payroll runs)
CREATE TABLE IF NOT EXISTS public.payroll (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         bigint NOT NULL REFERENCES public.employees(id) ON DELETE RESTRICT,
    period              text NOT NULL,  -- e.g. '2026-02'
    base_salary         numeric NOT NULL DEFAULT 0,
    total_allowances    numeric NOT NULL DEFAULT 0,
    total_deductions    numeric NOT NULL DEFAULT 0,
    net_salary          numeric NOT NULL DEFAULT 0,
    status              text NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'approved', 'paid')),
    approved_by         bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (employee_id, period)
);

ALTER TABLE public.payroll ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.payroll FOR ALL USING (true) WITH CHECK (true);

-- 11. payroll_payments (actual salary disbursements)
CREATE TABLE IF NOT EXISTS public.payroll_payments (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id      bigint NOT NULL REFERENCES public.payroll(id) ON DELETE RESTRICT,
    account_id      bigint NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
    payment_date    timestamptz NOT NULL DEFAULT now(),
    amount          numeric NOT NULL,
    method          text NOT NULL DEFAULT 'cash'
                    CHECK (method IN ('cash', 'bank', 'check')),
    notes           text,
    created_by      bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.payroll_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.payroll_payments FOR ALL USING (true) WITH CHECK (true);

-- 12. employee_advances (salary advances / loans)
CREATE TABLE IF NOT EXISTS public.employee_advances (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         bigint NOT NULL REFERENCES public.employees(id) ON DELETE RESTRICT,
    amount              numeric NOT NULL,
    remaining_amount    numeric NOT NULL,
    reason              text,
    status              text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'approved', 'repaid')),
    approved_by         bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    account_id          bigint REFERENCES public.accounts(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.employee_advances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.employee_advances FOR ALL USING (true) WITH CHECK (true);

-- 13. advance_deductions (monthly deduction from payroll to repay advance)
CREATE TABLE IF NOT EXISTS public.advance_deductions (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advance_id  bigint NOT NULL REFERENCES public.employee_advances(id) ON DELETE RESTRICT,
    payroll_id  bigint NOT NULL REFERENCES public.payroll(id) ON DELETE RESTRICT,
    amount      numeric NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.advance_deductions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.advance_deductions FOR ALL USING (true) WITH CHECK (true);

-- 14. attendance
CREATE TABLE IF NOT EXISTS public.attendance (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    work_date   date NOT NULL,
    check_in    time,
    check_out   time,
    status      text NOT NULL DEFAULT 'present'
                CHECK (status IN ('present', 'absent', 'late', 'leave', 'half_day')),
    notes       text,
    UNIQUE (employee_id, work_date)
);

ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.attendance FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- SEED: Default roles
-- ============================================================
INSERT INTO public.roles (name, description) VALUES
    ('admin',             'Full system access'),
    ('manager',           'Department manager with approval rights'),
    ('cashier',           'Point of sale and payment operations'),
    ('warehouse_keeper',  'Inventory and stock management'),
    ('accountant',        'Financial operations and reports'),
    ('salesperson',       'Sales and customer management')
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- SEED: Default permissions (all modules x all actions)
-- ============================================================
INSERT INTO public.permissions (module, action, description) VALUES
    -- Products
    ('products',        'create', 'Create products'),
    ('products',        'read',   'View products'),
    ('products',        'update', 'Edit products'),
    ('products',        'delete', 'Delete products'),
    -- Customers
    ('customers',       'create', 'Create customers'),
    ('customers',       'read',   'View customers'),
    ('customers',       'update', 'Edit customers'),
    ('customers',       'delete', 'Delete customers'),
    -- Sales Invoices
    ('invoices',        'create', 'Create invoices'),
    ('invoices',        'read',   'View invoices'),
    ('invoices',        'update', 'Edit invoices'),
    ('invoices',        'delete', 'Delete invoices'),
    -- Orders
    ('orders',          'create', 'Create orders'),
    ('orders',          'read',   'View orders'),
    ('orders',          'update', 'Edit orders'),
    ('orders',          'delete', 'Delete orders'),
    -- Suppliers
    ('suppliers',       'create', 'Create suppliers'),
    ('suppliers',       'read',   'View suppliers'),
    ('suppliers',       'update', 'Edit suppliers'),
    ('suppliers',       'delete', 'Delete suppliers'),
    -- Purchases
    ('purchases',       'create', 'Create purchase orders/invoices'),
    ('purchases',       'read',   'View purchase orders/invoices'),
    ('purchases',       'update', 'Edit purchase orders/invoices'),
    ('purchases',       'delete', 'Delete purchase orders/invoices'),
    -- Inventory
    ('inventory',       'create', 'Create stock movements'),
    ('inventory',       'read',   'View inventory'),
    ('inventory',       'update', 'Adjust inventory'),
    ('inventory',       'delete', 'Delete stock records'),
    -- Employees
    ('employees',       'create', 'Create employees'),
    ('employees',       'read',   'View employees'),
    ('employees',       'update', 'Edit employees'),
    ('employees',       'delete', 'Delete employees'),
    -- Payroll
    ('payroll',         'create', 'Generate payroll'),
    ('payroll',         'read',   'View payroll'),
    ('payroll',         'update', 'Edit/approve payroll'),
    ('payroll',         'delete', 'Delete payroll records'),
    -- Accounts
    ('accounts',        'create', 'Create accounts'),
    ('accounts',        'read',   'View accounts'),
    ('accounts',        'update', 'Edit accounts'),
    ('accounts',        'delete', 'Delete accounts'),
    -- Reports
    ('reports',         'read',   'View reports')
ON CONFLICT (module, action) DO NOTHING;

-- ============================================================
-- Grant admin role ALL permissions
-- ============================================================
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r
CROSS JOIN public.permissions p
WHERE r.name = 'admin'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- ============================================================
-- SEED: Default salary components
-- ============================================================
INSERT INTO public.salary_components (name, type) VALUES
    ('Housing Allowance',       'allowance'),
    ('Transportation Allowance','allowance'),
    ('Phone Allowance',         'allowance'),
    ('Food Allowance',          'allowance'),
    ('Overtime',                'allowance'),
    ('Commission',              'allowance'),
    ('Health Insurance',        'deduction'),
    ('Social Insurance',        'deduction'),
    ('Absence Deduction',       'deduction'),
    ('Late Deduction',          'deduction');

-- ============================================================
-- SEED: Default departments
-- ============================================================
INSERT INTO public.departments (name) VALUES
    ('Management'),
    ('Sales'),
    ('Warehouse'),
    ('Accounting'),
    ('Maintenance');
