-- ============================================================
-- SUPPLIERS MODULE - Migration Script
-- Run this AFTER employees module (001)
-- ============================================================

-- 1. supplier_types
CREATE TABLE IF NOT EXISTS public.supplier_types (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name   text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.supplier_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.supplier_types FOR ALL USING (true) WITH CHECK (true);

-- 2. suppliers
CREATE TABLE IF NOT EXISTS public.suppliers (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL,
    company_name        text,
    email               text,
    phone               text,
    phone2              text,
    address             text,
    tax_number          text,
    notes               text,
    is_active           boolean NOT NULL DEFAULT true,
    supplier_type_id    bigint REFERENCES public.supplier_types(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.suppliers FOR ALL USING (true) WITH CHECK (true);

-- 3. purchase_orders
CREATE TABLE IF NOT EXISTS public.purchase_orders (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id     bigint NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
    warehouse_id    bigint REFERENCES public.warehouses(id) ON DELETE SET NULL,
    order_date      timestamptz NOT NULL DEFAULT now(),
    total_amount    numeric NOT NULL DEFAULT 0,
    notes           text,
    status_id       bigint NOT NULL DEFAULT 1 REFERENCES public.order_statuses(id) ON DELETE RESTRICT,
    created_by      bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.purchase_orders FOR ALL USING (true) WITH CHECK (true);

-- 4. purchase_order_items
CREATE TABLE IF NOT EXISTS public.purchase_order_items (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id   bigint NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
    product_id          bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    product_unit_id     bigint REFERENCES public.product_units(id) ON DELETE SET NULL,
    quantity            integer NOT NULL DEFAULT 1,
    unit_cost           numeric NOT NULL DEFAULT 0,
    total_cost          numeric NOT NULL DEFAULT 0
);

ALTER TABLE public.purchase_order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.purchase_order_items FOR ALL USING (true) WITH CHECK (true);

-- 5. purchase_invoices
CREATE TABLE IF NOT EXISTS public.purchase_invoices (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         bigint NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
    purchase_order_id   bigint REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
    invoice_date        timestamptz NOT NULL DEFAULT now(),
    total_amount        numeric NOT NULL DEFAULT 0,
    paid_amount         numeric NOT NULL DEFAULT 0,
    status_id           bigint NOT NULL DEFAULT 1 REFERENCES public.invoice_statuses(id) ON DELETE RESTRICT,
    invoice_number      text,
    notes               text,
    created_by          bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.purchase_invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.purchase_invoices FOR ALL USING (true) WITH CHECK (true);

-- 6. purchase_invoice_items
CREATE TABLE IF NOT EXISTS public.purchase_invoice_items (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id     bigint NOT NULL REFERENCES public.purchase_invoices(id) ON DELETE CASCADE,
    product_id              bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
    product_unit_id         bigint REFERENCES public.product_units(id) ON DELETE SET NULL,
    quantity                integer NOT NULL DEFAULT 1,
    unit_cost               numeric NOT NULL DEFAULT 0,
    total_cost              numeric NOT NULL DEFAULT 0
);

ALTER TABLE public.purchase_invoice_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.purchase_invoice_items FOR ALL USING (true) WITH CHECK (true);

-- 7. supplier_payments
CREATE TABLE IF NOT EXISTS public.supplier_payments (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id     bigint NOT NULL REFERENCES public.purchase_invoices(id) ON DELETE RESTRICT,
    account_id              bigint NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
    payment_date            timestamptz NOT NULL DEFAULT now(),
    amount                  numeric NOT NULL,
    method                  text NOT NULL DEFAULT 'cash'
                            CHECK (method IN ('cash', 'bank', 'check')),
    notes                   text,
    created_by              bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at              timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.supplier_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.supplier_payments FOR ALL USING (true) WITH CHECK (true);

-- 8. purchase_returns
CREATE TABLE IF NOT EXISTS public.purchase_returns (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_item_id    bigint NOT NULL REFERENCES public.purchase_invoice_items(id) ON DELETE RESTRICT,
    return_date                 timestamptz NOT NULL DEFAULT now(),
    quantity                    integer NOT NULL,
    reason                      text,
    credit_amount               numeric NOT NULL DEFAULT 0,
    status_id                   bigint NOT NULL DEFAULT 1 REFERENCES public.return_statuses(id) ON DELETE RESTRICT,
    created_by                  bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at                  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.purchase_returns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access for anon" ON public.purchase_returns FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- SEED: Default supplier types
-- ============================================================
INSERT INTO public.supplier_types (type_name) VALUES
    ('Local'),
    ('International'),
    ('Manufacturer'),
    ('Distributor'),
    ('Agent')
ON CONFLICT (type_name) DO NOTHING;

-- ============================================================
-- INDEXES for performance
-- ============================================================

-- Suppliers
CREATE INDEX IF NOT EXISTS idx_suppliers_type ON public.suppliers(supplier_type_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_active ON public.suppliers(is_active);

-- Purchase Orders
CREATE INDEX IF NOT EXISTS idx_purchase_orders_supplier ON public.purchase_orders(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_status ON public.purchase_orders(status_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_date ON public.purchase_orders(order_date);

-- Purchase Order Items
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_order ON public.purchase_order_items(purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_product ON public.purchase_order_items(product_id);

-- Purchase Invoices
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_supplier ON public.purchase_invoices(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_status ON public.purchase_invoices(status_id);
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_date ON public.purchase_invoices(invoice_date);

-- Purchase Invoice Items
CREATE INDEX IF NOT EXISTS idx_purchase_invoice_items_invoice ON public.purchase_invoice_items(purchase_invoice_id);
CREATE INDEX IF NOT EXISTS idx_purchase_invoice_items_product ON public.purchase_invoice_items(product_id);

-- Supplier Payments
CREATE INDEX IF NOT EXISTS idx_supplier_payments_invoice ON public.supplier_payments(purchase_invoice_id);
CREATE INDEX IF NOT EXISTS idx_supplier_payments_account ON public.supplier_payments(account_id);

-- Purchase Returns
CREATE INDEX IF NOT EXISTS idx_purchase_returns_item ON public.purchase_returns(purchase_invoice_item_id);
CREATE INDEX IF NOT EXISTS idx_purchase_returns_status ON public.purchase_returns(status_id);

-- Employees
CREATE INDEX IF NOT EXISTS idx_employees_department ON public.employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_job_title ON public.employees(job_title_id);
CREATE INDEX IF NOT EXISTS idx_employees_active ON public.employees(is_active);
CREATE INDEX IF NOT EXISTS idx_employees_auth ON public.employees(auth_user_id);

-- Payroll
CREATE INDEX IF NOT EXISTS idx_payroll_employee ON public.payroll(employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_period ON public.payroll(period);
CREATE INDEX IF NOT EXISTS idx_payroll_status ON public.payroll(status);

-- Payroll Payments
CREATE INDEX IF NOT EXISTS idx_payroll_payments_payroll ON public.payroll_payments(payroll_id);

-- Employee Advances
CREATE INDEX IF NOT EXISTS idx_employee_advances_employee ON public.employee_advances(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_advances_status ON public.employee_advances(status);

-- Attendance
CREATE INDEX IF NOT EXISTS idx_attendance_employee ON public.attendance(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance(work_date);
