-- ============================================================
-- JOURNAL ENTRIES MODULE  –  Full Double-Entry Bookkeeping
-- Run AFTER 000, 001, 002
-- ============================================================

-- Drop old flat journal_entries table (incompatible schema)
DROP TABLE IF EXISTS public.journal_entry_lines CASCADE;
DROP TABLE IF EXISTS public.journal_entries CASCADE;

-- ============================================================
-- 1. fiscal_years
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fiscal_years (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_label  text NOT NULL UNIQUE,            -- e.g. '2026'
    start_date  date NOT NULL,
    end_date    date NOT NULL,
    is_closed   boolean NOT NULL DEFAULT false,
    closed_by   bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    closed_at   timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.fiscal_years ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow full access for anon" ON public.fiscal_years FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- 2. journal_entries  (header)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.journal_entries (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_number      text UNIQUE,                -- auto JE-000001
    entry_date        date NOT NULL DEFAULT CURRENT_DATE,
    transaction_type  text NOT NULL DEFAULT 'manual'
                      CHECK (transaction_type IN (
                        'manual','payment','receipt','purchase','expense',
                        'salary','advance','return','adjustment',
                        'opening','closing','transfer'
                      )),
    description       text,
    reference         text,
    source_type       text,                       -- e.g. 'payment','payroll'
    source_id         bigint,                     -- FK to the originating record
    is_posted         boolean NOT NULL DEFAULT false,
    posted_at         timestamptz,
    is_reversed       boolean NOT NULL DEFAULT false,
    reversed_by_id    bigint REFERENCES public.journal_entries(id) ON DELETE SET NULL,
    created_by        bigint REFERENCES public.employees(id) ON DELETE SET NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow full access for anon" ON public.journal_entries FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_je_date         ON public.journal_entries(entry_date);
CREATE INDEX IF NOT EXISTS idx_je_type         ON public.journal_entries(transaction_type);
CREATE INDEX IF NOT EXISTS idx_je_posted       ON public.journal_entries(is_posted);
CREATE INDEX IF NOT EXISTS idx_je_source       ON public.journal_entries(source_type, source_id);

DROP TRIGGER IF EXISTS trg_journal_entries_updated_at ON public.journal_entries;
CREATE TRIGGER trg_journal_entries_updated_at
  BEFORE UPDATE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- 3. journal_entry_lines  (detail – debits & credits)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.journal_entry_lines (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id  bigint NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
    account_id        bigint NOT NULL REFERENCES public.accounts(id) ON DELETE RESTRICT,
    debit             numeric NOT NULL DEFAULT 0,
    credit            numeric NOT NULL DEFAULT 0,
    description       text,                       -- line-level memo
    cost_center       text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CHECK ((debit  > 0 AND credit = 0) OR
           (debit  = 0 AND credit > 0))
);

ALTER TABLE public.journal_entry_lines ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY "Allow full access for anon" ON public.journal_entry_lines FOR ALL USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_jel_entry   ON public.journal_entry_lines(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_jel_account ON public.journal_entry_lines(account_id);

-- ============================================================
-- TRIGGER 1: Auto-generate entry_number  JE-000001
-- ============================================================
CREATE OR REPLACE FUNCTION public.generate_entry_number()
RETURNS trigger AS $$
DECLARE
  next_num integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(entry_number FROM 4) AS integer)), 0) + 1
    INTO next_num
    FROM public.journal_entries;
  NEW.entry_number := 'JE-' || LPAD(next_num::text, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_je_entry_number ON public.journal_entries;
CREATE TRIGGER trg_je_entry_number
  BEFORE INSERT ON public.journal_entries
  FOR EACH ROW
  WHEN (NEW.entry_number IS NULL)
  EXECUTE FUNCTION public.generate_entry_number();

-- ============================================================
-- TRIGGER 2: Validate SUM(debit) = SUM(credit)  (DEFERRED)
-- ============================================================
CREATE OR REPLACE FUNCTION public.validate_journal_balance()
RETURNS trigger AS $$
DECLARE
  total_debit  numeric;
  total_credit numeric;
BEGIN
  SELECT COALESCE(SUM(debit), 0), COALESCE(SUM(credit), 0)
    INTO total_debit, total_credit
    FROM public.journal_entry_lines
   WHERE journal_entry_id = COALESCE(NEW.journal_entry_id, OLD.journal_entry_id);

  IF total_debit <> total_credit THEN
    RAISE EXCEPTION 'Journal entry is not balanced: debit=% credit=%',
      total_debit, total_credit;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_je_balance_check ON public.journal_entry_lines;
CREATE CONSTRAINT TRIGGER trg_je_balance_check
  AFTER INSERT OR UPDATE OR DELETE ON public.journal_entry_lines
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_journal_balance();

-- ============================================================
-- TRIGGER 3: Recalculate account balances when entry is posted
-- ============================================================
CREATE OR REPLACE FUNCTION public.recalc_account_balances()
RETURNS trigger AS $$
BEGIN
  -- Only act when is_posted changes to true
  IF NEW.is_posted = true AND (OLD.is_posted IS DISTINCT FROM true) THEN
    UPDATE public.accounts a
       SET balance = a.opening_balance + COALESCE(agg.net, 0)
      FROM (
        SELECT jel.account_id,
               SUM(CASE WHEN ac.account_type IN ('asset','expense')
                        THEN jel.debit - jel.credit
                        ELSE jel.credit - jel.debit END) AS net
          FROM public.journal_entry_lines jel
          JOIN public.journal_entries je ON je.id = jel.journal_entry_id
          JOIN public.accounts ac ON ac.id = jel.account_id
         WHERE je.is_posted = true
         GROUP BY jel.account_id
      ) agg
     WHERE a.id = agg.account_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_je_recalc_balances ON public.journal_entries;
CREATE TRIGGER trg_je_recalc_balances
  AFTER UPDATE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.recalc_account_balances();

-- ============================================================
-- TRIGGER 4: Prevent editing posted entries' lines
-- ============================================================
CREATE OR REPLACE FUNCTION public.prevent_posted_edit()
RETURNS trigger AS $$
DECLARE
  posted boolean;
BEGIN
  SELECT is_posted INTO posted
    FROM public.journal_entries
   WHERE id = COALESCE(OLD.journal_entry_id, NEW.journal_entry_id);

  IF posted = true THEN
    RAISE EXCEPTION 'Cannot modify lines of a posted journal entry';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_jel_prevent_posted ON public.journal_entry_lines;
CREATE TRIGGER trg_jel_prevent_posted
  BEFORE UPDATE OR DELETE ON public.journal_entry_lines
  FOR EACH ROW EXECUTE FUNCTION public.prevent_posted_edit();

-- ============================================================
-- TRIGGER 5: Prevent entries in closed fiscal years
-- ============================================================
CREATE OR REPLACE FUNCTION public.prevent_closed_period()
RETURNS trigger AS $$
DECLARE
  yr_closed boolean;
BEGIN
  SELECT is_closed INTO yr_closed
    FROM public.fiscal_years
   WHERE NEW.entry_date BETWEEN start_date AND end_date
   LIMIT 1;

  IF yr_closed = true THEN
    RAISE EXCEPTION 'Cannot create entries in a closed fiscal period';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_je_closed_period ON public.journal_entries;
CREATE TRIGGER trg_je_closed_period
  BEFORE INSERT ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.prevent_closed_period();

-- ============================================================
-- TRIGGER 6: Sync invoice paid_amount from payments
-- ============================================================
CREATE OR REPLACE FUNCTION public.sync_invoice_paid_amount()
RETURNS trigger AS $$
DECLARE
  inv_id bigint;
BEGIN
  inv_id := COALESCE(NEW.invoice_id, OLD.invoice_id);
  UPDATE public.invoices
     SET paid_amount = COALESCE((
           SELECT SUM(amount) FROM public.payments WHERE invoice_id = inv_id
         ), 0)
   WHERE id = inv_id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_payments_sync ON public.payments;
CREATE TRIGGER trg_payments_sync
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_invoice_paid_amount();

-- ============================================================
-- TRIGGER 7: Sync purchase_invoice paid_amount from supplier_payments
-- ============================================================
CREATE OR REPLACE FUNCTION public.sync_purchase_invoice_paid()
RETURNS trigger AS $$
DECLARE
  inv_id bigint;
BEGIN
  inv_id := COALESCE(NEW.purchase_invoice_id, OLD.purchase_invoice_id);
  UPDATE public.purchase_invoices
     SET paid_amount = COALESCE((
           SELECT SUM(amount) FROM public.supplier_payments WHERE purchase_invoice_id = inv_id
         ), 0)
   WHERE id = inv_id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_supplier_payments_sync ON public.supplier_payments;
CREATE TRIGGER trg_supplier_payments_sync
  AFTER INSERT OR UPDATE OR DELETE ON public.supplier_payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_purchase_invoice_paid();

-- ============================================================
-- TRIGGER 8: Auto-compute payroll net_salary
-- ============================================================
CREATE OR REPLACE FUNCTION public.compute_payroll_net()
RETURNS trigger AS $$
BEGIN
  NEW.net_salary := NEW.base_salary + NEW.total_allowances - NEW.total_deductions;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_payroll_net ON public.payroll;
CREATE TRIGGER trg_payroll_net
  BEFORE INSERT OR UPDATE ON public.payroll
  FOR EACH ROW EXECUTE FUNCTION public.compute_payroll_net();

-- ============================================================
-- TRIGGER 9: Sync advance remaining_amount from deductions
-- ============================================================
CREATE OR REPLACE FUNCTION public.sync_advance_remaining()
RETURNS trigger AS $$
DECLARE
  adv_id bigint;
BEGIN
  adv_id := COALESCE(NEW.advance_id, OLD.advance_id);
  UPDATE public.employee_advances
     SET remaining_amount = amount - COALESCE((
           SELECT SUM(amount) FROM public.advance_deductions WHERE advance_id = adv_id
         ), 0)
   WHERE id = adv_id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_advance_deductions_sync ON public.advance_deductions;
CREATE TRIGGER trg_advance_deductions_sync
  AFTER INSERT OR UPDATE OR DELETE ON public.advance_deductions
  FOR EACH ROW EXECUTE FUNCTION public.sync_advance_remaining();

-- ============================================================
-- RPC 1: Create journal entry for a payment (customer or supplier)
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_payment_journal_entry(
  p_payment_id  bigint,
  p_source      text        -- 'customer' or 'supplier'
)
RETURNS bigint AS $$
DECLARE
  v_je_id       bigint;
  v_amount      numeric;
  v_account_id  bigint;
  v_description text;
  v_cash_acct   bigint;
  v_recv_acct   bigint;
  v_pay_acct    bigint;
BEGIN
  -- Resolve system accounts
  SELECT id INTO v_cash_acct FROM public.accounts WHERE account_code = '1001' LIMIT 1;
  SELECT id INTO v_recv_acct FROM public.accounts WHERE account_code = '1200' LIMIT 1;
  SELECT id INTO v_pay_acct  FROM public.accounts WHERE account_code = '2100' LIMIT 1;

  IF p_source = 'customer' THEN
    SELECT amount, account_id INTO v_amount, v_account_id
      FROM public.payments WHERE id = p_payment_id;
    v_description := 'Customer payment #' || p_payment_id;

    INSERT INTO public.journal_entries (entry_date, transaction_type, description, source_type, source_id, is_posted, posted_at)
    VALUES (CURRENT_DATE, 'receipt', v_description, 'payment', p_payment_id, true, now())
    RETURNING id INTO v_je_id;

    INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, debit, credit, description)
    VALUES (v_je_id, COALESCE(v_account_id, v_cash_acct), v_amount, 0, 'Cash/Bank received'),
           (v_je_id, v_recv_acct, 0, v_amount, 'Accounts receivable cleared');

  ELSIF p_source = 'supplier' THEN
    SELECT amount, account_id INTO v_amount, v_account_id
      FROM public.supplier_payments WHERE id = p_payment_id;
    v_description := 'Supplier payment #' || p_payment_id;

    INSERT INTO public.journal_entries (entry_date, transaction_type, description, source_type, source_id, is_posted, posted_at)
    VALUES (CURRENT_DATE, 'payment', v_description, 'supplier_payment', p_payment_id, true, now())
    RETURNING id INTO v_je_id;

    INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, debit, credit, description)
    VALUES (v_je_id, v_pay_acct, v_amount, 0, 'Accounts payable cleared'),
           (v_je_id, COALESCE(v_account_id, v_cash_acct), 0, v_amount, 'Cash/Bank paid');
  END IF;

  RETURN v_je_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- RPC 2: Create journal entry for payroll
-- ============================================================
CREATE OR REPLACE FUNCTION public.create_payroll_journal_entry(p_payroll_id bigint)
RETURNS bigint AS $$
DECLARE
  v_je_id      bigint;
  v_net        numeric;
  v_salary_acct bigint;
  v_cash_acct   bigint;
BEGIN
  SELECT id INTO v_salary_acct FROM public.accounts WHERE account_code = '5100' LIMIT 1;
  SELECT id INTO v_cash_acct   FROM public.accounts WHERE account_code = '1001' LIMIT 1;

  SELECT net_salary INTO v_net FROM public.payroll WHERE id = p_payroll_id;

  INSERT INTO public.journal_entries (entry_date, transaction_type, description, source_type, source_id, is_posted, posted_at)
  VALUES (CURRENT_DATE, 'salary', 'Payroll #' || p_payroll_id, 'payroll', p_payroll_id, true, now())
  RETURNING id INTO v_je_id;

  INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, debit, credit, description)
  VALUES (v_je_id, v_salary_acct, v_net, 0, 'Salary expense'),
         (v_je_id, v_cash_acct,   0, v_net, 'Cash paid');

  RETURN v_je_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- RPC 3: Reverse a journal entry
-- ============================================================
CREATE OR REPLACE FUNCTION public.reverse_journal_entry(p_entry_id bigint)
RETURNS bigint AS $$
DECLARE
  v_new_id bigint;
  v_orig   record;
BEGIN
  SELECT * INTO v_orig FROM public.journal_entries WHERE id = p_entry_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Entry not found'; END IF;
  IF v_orig.is_reversed THEN RAISE EXCEPTION 'Entry already reversed'; END IF;

  INSERT INTO public.journal_entries (entry_date, transaction_type, description, reference, source_type, source_id, is_posted, posted_at)
  VALUES (CURRENT_DATE, v_orig.transaction_type,
          'Reversal of ' || v_orig.entry_number,
          v_orig.entry_number, v_orig.source_type, v_orig.source_id,
          true, now())
  RETURNING id INTO v_new_id;

  -- Insert swapped lines
  INSERT INTO public.journal_entry_lines (journal_entry_id, account_id, debit, credit, description, cost_center)
  SELECT v_new_id, account_id, credit, debit, 'Reversal: ' || COALESCE(description,''), cost_center
    FROM public.journal_entry_lines
   WHERE journal_entry_id = p_entry_id;

  -- Mark original as reversed
  UPDATE public.journal_entries
     SET is_reversed = true, reversed_by_id = v_new_id
   WHERE id = p_entry_id;

  RETURN v_new_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- VIEW: Trial Balance
-- ============================================================
CREATE OR REPLACE VIEW public.trial_balance AS
SELECT
  a.id            AS account_id,
  a.account_code,
  a.name          AS account_name,
  a.account_type,
  a.account_subtype,
  COALESCE(SUM(jel.debit), 0)  AS total_debit,
  COALESCE(SUM(jel.credit), 0) AS total_credit,
  CASE WHEN a.account_type IN ('asset','expense')
       THEN a.opening_balance + COALESCE(SUM(jel.debit), 0) - COALESCE(SUM(jel.credit), 0)
       ELSE a.opening_balance + COALESCE(SUM(jel.credit), 0) - COALESCE(SUM(jel.debit), 0)
  END AS balance
FROM public.accounts a
LEFT JOIN public.journal_entry_lines jel ON jel.account_id = a.id
LEFT JOIN public.journal_entries je ON je.id = jel.journal_entry_id AND je.is_posted = true
GROUP BY a.id, a.account_code, a.name, a.account_type, a.account_subtype, a.opening_balance;

-- ============================================================
-- VIEW: Account Ledger  (line-by-line history)
-- ============================================================
CREATE OR REPLACE VIEW public.account_ledger AS
SELECT
  jel.id           AS line_id,
  a.id             AS account_id,
  a.account_code,
  a.name           AS account_name,
  je.id            AS journal_entry_id,
  je.entry_number,
  je.entry_date,
  je.description   AS entry_description,
  jel.debit,
  jel.credit,
  jel.description  AS line_description,
  jel.cost_center
FROM public.journal_entry_lines jel
JOIN public.journal_entries je ON je.id = jel.journal_entry_id
JOIN public.accounts a ON a.id = jel.account_id
WHERE je.is_posted = true
ORDER BY je.entry_date, je.id, jel.id;

-- ============================================================
-- SEED: Default fiscal year
-- ============================================================
INSERT INTO public.fiscal_years (year_label, start_date, end_date)
VALUES ('2026', '2026-01-01', '2026-12-31')
ON CONFLICT (year_label) DO NOTHING;
